version: 2.1

orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.3

jobs:
  vulnerability_scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - bridgecrew/install
      - bridgecrew/scan:
          directory: terraform/aws/  
workflows:
  workflow:
    jobs:
      - vulnerability_scan
